name: Build & Deploy Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Check out repo
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3. Install uv
      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      # 4. Use uv to install dependencies from pyproject.toml / uv.lock
      - name: Install project dependencies with uv
        run: |
          uv sync

      # 5. Build the docs
      - name: Build Sphinx docs
        run: |
          cd docs
          make html

      # 6. Copy the generated HTML into site/
      - name: Copy HTML to site/
        run: |
          rm -rf site  # remove old site folder if it exists
          mkdir -p site
          cp -r docs/_build/html/* site/

      # 7. Commit and push changes back to the repo
      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add site
          # The commit command will fail if there are no changes, so we catch that
          git commit -m "Update Sphinx docs [skip ci]" || echo "No changes to commit"
          git push
